apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-frontend
  labels:
    {{- include "todo-app.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
  - name: http
    port: {{ .Values.service.frontend.port }}
    targetPort: {{ .Values.service.frontend.targetPort }}
    {{- if eq .Values.service.frontend.type "NodePort" }}
    nodePort: {{ .Values.service.frontend.nodePort }}
    {{- end }}
    protocol: TCP
  selector:
    {{- include "todo-app.frontend.selectorLabels" . | nindent 4 }}
